export const projectList = [
  {
    id: 1,
    ident: "ENG",
    name: "Engineering Platform",
    desc: "Core backend services, API gateway, and developer tooling for the platform.",
    visibility: "public",
    type: "Software",
    progress: 67,
    members: ["SC", "AA", "ML", "TS", "RK"],
    issues: 48,
    open: 16,
    overdue: 3,
    updated: "2h ago",
    archived: false,
  },
  {
    id: 2,
    ident: "MKT",
    name: "Marketing Site v3",
    desc: "Complete redesign of the marketing website with new brand guidelines.",
    visibility: "public",
    type: "Marketing",
    progress: 34,
    members: ["AA", "JD"],
    issues: 22,
    open: 14,
    overdue: 2,
    updated: "4h ago",
    archived: false,
  },
  {
    id: 3,
    ident: "MOB",
    name: "Mobile App v2",
    desc: "iOS and Android application with offline-first architecture.",
    visibility: "private",
    type: "Software",
    progress: 12,
    members: ["ML", "TS", "SC"],
    issues: 65,
    open: 54,
    overdue: 8,
    updated: "1d ago",
    archived: false,
  },
  {
    id: 4,
    ident: "DSN",
    name: "Design System",
    desc: "Component library and design tokens for consistent UI across products.",
    visibility: "public",
    type: "Design",
    progress: 89,
    members: ["JD", "AA"],
    issues: 31,
    open: 3,
    overdue: 0,
    updated: "3d ago",
    archived: false,
  },
  {
    id: 5,
    ident: "OPS",
    name: "DevOps & Infrastructure",
    desc: "CI/CD pipelines, Kubernetes clusters, and monitoring setup.",
    visibility: "private",
    type: "Operations",
    progress: 55,
    members: ["TS", "RK", "AA"],
    issues: 19,
    open: 8,
    overdue: 1,
    updated: "5d ago",
    archived: false,
  },
  {
    id: 6,
    ident: "LEG",
    name: "Legacy API",
    desc: "Maintenance of the legacy REST API before full migration.",
    visibility: "private",
    type: "Software",
    progress: 100,
    members: ["RK"],
    issues: 12,
    open: 0,
    overdue: 0,
    updated: "2w ago",
    archived: true,
  },
];

export const boardColumns = [
  { id: "backlog", label: "Backlog", status: "status-backlog" },
  { id: "todo", label: "Todo", status: "status-todo" },
  { id: "inprogress", label: "In Progress", status: "status-inprogress" },
  { id: "inreview", label: "In Review", status: "status-inreview" },
  { id: "done", label: "Done", status: "status-done" },
  { id: "blocked", label: "Blocked", status: "status-blocked" },
];

export const boardIssues = [
  {
    id: 1,
    ident: "ENG-42",
    title: "Fix authentication bug in OAuth flow",
    priority: "urgent",
    status: "inprogress",
    labels: ["bug"],
    assignee: "SC",
    due: "Apr 25",
    overdue: false,
    subtasks: "2/5",
  },
  {
    id: 2,
    ident: "ENG-38",
    title: "User onboarding flow redesign",
    priority: "high",
    status: "inreview",
    labels: ["feature", "design"],
    assignee: "ML",
    due: "Apr 28",
    overdue: false,
    subtasks: "4/4",
    typing: true,
  },
  {
    id: 3,
    ident: "ENG-45",
    title: "API rate limiting implementation",
    priority: "medium",
    status: "todo",
    labels: ["feature"],
    assignee: "TS",
    due: "Apr 30",
    overdue: false,
  },
  {
    id: 4,
    ident: "ENG-31",
    title: "Dashboard analytics redesign",
    priority: "high",
    status: "done",
    labels: ["design"],
    assignee: "AA",
    due: "Apr 20",
    overdue: false,
  },
  {
    id: 5,
    ident: "ENG-29",
    title: "Database connection pool leak",
    priority: "urgent",
    status: "blocked",
    labels: ["bug", "perf"],
    assignee: "TS",
    due: "Apr 22",
    overdue: true,
  },
  {
    id: 6,
    ident: "ENG-46",
    title: "Performance audit for main API endpoints",
    priority: "medium",
    status: "backlog",
    labels: ["perf"],
    assignee: "SC",
    due: "May 5",
    overdue: false,
  },
  {
    id: 7,
    ident: "ENG-47",
    title: "Add dark mode support to settings page",
    priority: "low",
    status: "todo",
    labels: ["feature"],
    assignee: "ML",
    due: "May 10",
    overdue: false,
  },
  {
    id: 8,
    ident: "ENG-48",
    title: "Write unit tests for auth module",
    priority: "medium",
    status: "inprogress",
    labels: ["docs"],
    assignee: "AA",
    due: "Apr 26",
    overdue: false,
  },
];
