export const projectList = [
  {
    id: 1,
    ident: "ENG",
    name: "Engineering Platform",
    desc: "Core backend services, API gateway, and developer tooling for the platform.",
    visibility: "public",
    type: "Software",
    progress: 67,
    members: ["SC", "AA", "ML", "TS", "RK"],
    issues: 48,
    open: 16,
    overdue: 3,
    updated: "2h ago",
    archived: false,
  },
  {
    id: 2,
    ident: "MKT",
    name: "Marketing Site v3",
    desc: "Complete redesign of the marketing website with new brand guidelines.",
    visibility: "public",
    type: "Marketing",
    progress: 34,
    members: ["AA", "JD"],
    issues: 22,
    open: 14,
    overdue: 2,
    updated: "4h ago",
    archived: false,
  },
  {
    id: 3,
    ident: "MOB",
    name: "Mobile App v2",
    desc: "iOS and Android application with offline-first architecture.",
    visibility: "private",
    type: "Software",
    progress: 12,
    members: ["ML", "TS", "SC"],
    issues: 65,
    open: 54,
    overdue: 8,
    updated: "1d ago",
    archived: false,
  },
  {
    id: 4,
    ident: "DSN",
    name: "Design System",
    desc: "Component library and design tokens for consistent UI across products.",
    visibility: "public",
    type: "Design",
    progress: 89,
    members: ["JD", "AA"],
    issues: 31,
    open: 3,
    overdue: 0,
    updated: "3d ago",
    archived: false,
  },
  {
    id: 5,
    ident: "OPS",
    name: "DevOps & Infrastructure",
    desc: "CI/CD pipelines, Kubernetes clusters, and monitoring setup.",
    visibility: "private",
    type: "Operations",
    progress: 55,
    members: ["TS", "RK", "AA"],
    issues: 19,
    open: 8,
    overdue: 1,
    updated: "5d ago",
    archived: false,
  },
  {
    id: 6,
    ident: "LEG",
    name: "Legacy API",
    desc: "Maintenance of the legacy REST API before full migration.",
    visibility: "private",
    type: "Software",
    progress: 100,
    members: ["RK"],
    issues: 12,
    open: 0,
    overdue: 0,
    updated: "2w ago",
    archived: true,
  },
];

export const boardColumns = [
  { id: "backlog", label: "Backlog", status: "status-backlog" },
  { id: "todo", label: "Todo", status: "status-todo" },
  { id: "inprogress", label: "In Progress", status: "status-inprogress" },
  { id: "inreview", label: "In Review", status: "status-inreview" },
  { id: "done", label: "Done", status: "status-done" },
  { id: "blocked", label: "Blocked", status: "status-blocked" },
];

export const boardIssues = [
  {
    id: 1,
    ident: "ENG-42",
    title: "Fix authentication bug in OAuth flow",
    priority: "urgent",
    status: "inprogress",
    labels: ["bug"],
    assignee: "SC",
    due: "Apr 25",
    overdue: false,
    subtasks: "2/5",
  },
  {
    id: 2,
    ident: "ENG-38",
    title: "User onboarding flow redesign",
    priority: "high",
    status: "inreview",
    labels: ["feature", "design"],
    assignee: "ML",
    due: "Apr 28",
    overdue: false,
    subtasks: "4/4",
    typing: true,
  },
  {
    id: 3,
    ident: "ENG-45",
    title: "API rate limiting implementation",
    priority: "medium",
    status: "todo",
    labels: ["feature"],
    assignee: "TS",
    due: "Apr 30",
    overdue: false,
  },
  {
    id: 4,
    ident: "ENG-31",
    title: "Dashboard analytics redesign",
    priority: "high",
    status: "done",
    labels: ["design"],
    assignee: "AA",
    due: "Apr 20",
    overdue: false,
  },
  {
    id: 5,
    ident: "ENG-29",
    title: "Database connection pool leak",
    priority: "urgent",
    status: "blocked",
    labels: ["bug", "perf"],
    assignee: "TS",
    due: "Apr 22",
    overdue: true,
  },
  {
    id: 6,
    ident: "ENG-46",
    title: "Performance audit for main API endpoints",
    priority: "medium",
    status: "backlog",
    labels: ["perf"],
    assignee: "SC",
    due: "May 5",
    overdue: false,
  },
  {
    id: 7,
    ident: "ENG-47",
    title: "Add dark mode support to settings page",
    priority: "low",
    status: "todo",
    labels: ["feature"],
    assignee: "ML",
    due: "May 10",
    overdue: false,
  },
  {
    id: 8,
    ident: "ENG-48",
    title: "Write unit tests for auth module",
    priority: "medium",
    status: "inprogress",
    labels: ["docs"],
    assignee: "AA",
    due: "Apr 26",
    overdue: false,
  },
];

// members
export const projectMembers = [
  {
    id: 1,
    name: "Alex Admin",
    email: "alex@example.com",
    prole: "Manager",
    initials: "AA",
    assigned: 0,
    added: "Jan 10, 2026",
  },
  {
    id: 2,
    name: "Sarah Chen",
    email: "sarah@example.com",
    prole: "Member",
    initials: "SC",
    assigned: 5,
    added: "Jan 15, 2026",
  },
  {
    id: 3,
    name: "Tom Singh",
    email: "tom@example.com",
    prole: "Member",
    initials: "TS",
    assigned: 3,
    added: "Feb 2, 2026",
  },
];

// backlog
export const sprintBacklogs = [
  {
    id: "s5",
    name: "Sprint 5",
    status: "active",
    dates: "Apr 20 – May 3",
    issues: [
      {
        id: 1,
        ident: "ENG-42",
        title: "Fix authentication bug in OAuth flow",
        priority: "urgent",
        status: "inprogress",
        assignee: "SC",
        points: 5,
        due: "Apr 25",
        type: "bug",
      },
      {
        id: 2,
        ident: "ENG-38",
        title: "User onboarding flow redesign",
        priority: "high",
        status: "inreview",
        assignee: "ML",
        points: 8,
        due: "Apr 28",
        type: "feature",
      },
      {
        id: 3,
        ident: "ENG-45",
        title: "API rate limiting implementation",
        priority: "medium",
        status: "todo",
        assignee: "TS",
        points: 3,
        due: "Apr 30",
        type: "feature",
      },
      {
        id: 4,
        ident: "ENG-48",
        title: "Write unit tests for auth module",
        priority: "medium",
        status: "inprogress",
        assignee: "AA",
        points: 3,
        due: "Apr 26",
        type: "task",
      },
    ],
  },
  {
    id: "s6",
    name: "Sprint 6",
    status: "planned",
    dates: "May 4 – May 17",
    issues: [
      {
        id: 5,
        ident: "ENG-46",
        title: "Performance audit for main API endpoints",
        priority: "medium",
        status: "backlog",
        assignee: "SC",
        points: 5,
        due: "May 10",
        type: "task",
      },
      {
        id: 6,
        ident: "ENG-47",
        title: "Add dark mode support to settings page",
        priority: "low",
        status: "backlog",
        assignee: "ML",
        points: 2,
        due: "May 12",
        type: "feature",
      },
    ],
  },
];

export const backlogIssues = [
  {
    id: 7,
    ident: "ENG-49",
    title: "Mobile push notification support",
    priority: "high",
    status: "backlog",
    assignee: "TS",
    points: 8,
    due: "TBD",
    type: "feature",
  },
  {
    id: 8,
    ident: "ENG-50",
    title: "Export data to CSV / PDF",
    priority: "medium",
    status: "backlog",
    assignee: null,
    points: 3,
    due: "TBD",
    type: "feature",
  },
  {
    id: 9,
    ident: "ENG-51",
    title: "Accessibility audit and WCAG fixes",
    priority: "low",
    status: "backlog",
    assignee: null,
    points: 5,
    due: "TBD",
    type: "task",
  },
];
